### PR TITLE
adds more generator examples and other minor clarifications

### PR DESCRIPTION
**Pull request by danthareja**
Awesome resource! 

I'm really excited about generators in ES6 and wanted to add a few more examples of their use case. I added a basic use case and a yield* example

screen shot 2015-03-07 at 9 50 27 am
screen shot 2015-03-07 at 9 49 50 am

### CODE REVIEW

**Comment by lukehoban** [comment]
Thanks!  These additions look good.  

I've been aiming to keep this at ~1 page per feature, to make sure it stays an easy to consume overview of everything.  Do you think there's a way to cover `yield*` and the basic generator usage with more compact examples?

**Comment by danthareja** [comment]
Ah, if the goal is an overview, we could probably leave yield* out. I do still like the idea of a the basic usage though. How's the latest look? Close enough to 1 page?

**Comment by KenPowers** [comment]
What about a folder with extended examples for individual features? That way `README.md` can stay short for easy consumption but those of us seeking to go farther can have a one-stop resource for everything ES6.

**Comment by danthareja** [comment]
ooh I like that idea @KenPowers. Thoughts @lukehoban?

**Comment by getify** [comment]
IMO, I don't think it's a terribly useful idea to pepper this repo (even in subdirs) with more complete/complex examples of these features. This repo doesn't come across to me as an exhaustive encyclopedia of ES6, but rather a brief overview, like a marketing brochure.

FWIW, there's several other comprehensive ES6 resources (books, mostly) being written online which I think would be more effective to point to as a "see more and deeper examples here" list rather than duplicating those efforts.

I've got a running list here to consider: https://gist.github.com/getify/7ae82fdc2e86bf66bcba

**Comment by lukehoban** [comment]
I agree with @getify - there will be other great resources that are more complete. I think the unique value of this particular resource is that you can get a quick sense of all of the ES6 feature in a single read.  I'm not sure building up more complete examples here is more valuable than contributing those into other resources that are better suited to that purpose.

**Comment by danthareja** [comment]
Fair enough, cheers!

**Pull request closed without merging**
