### PR TITLE
Mention that arrow functions don't need `return`

### PR DESCRIPTION
**Pull request by Flimm**

### CODE REVIEW

**Comment by KenPowers** [comment]
As far as I'm aware this only applies to single-line arrow functions. Observe:

image

**Comment by domenic** [comment]
Indeed, this PR is incorrect. The expression-bodied case is already covered by the existing text.

**Comment by Flimm** [comment]
I've corrected the mistake. In `master`, the example does demonstrate that `return` is not required for the expression-bodied case, but it does not demonstrate that `return` *is* required for the statement-bodied case.

**Comment by getify** [comment]
Yes, but the point of this project is not to educate on all aspects of JS, not even all aspects of ES6. The point of this project is to highlight in a high-level way what new stuff people can get with ES6. There's tons of nuances to ES6 that aren't even remotely covered here. That's the job of comprehensive ES6 books. FWIW, I have a running list of them here: https://gist.github.com/getify/7ae82fdc2e86bf66bcba

**Comment by Flimm** [comment]
I'll leave it to you to decide whether this is a nuance or a pretty essential part of how arrow functions work. I would say it's on the same level of importance as the sentence "Unlike functions, arrows share the same lexical this as their surrounding code."

**Comment by getify** [comment]
> I would say it's on the same level of importance as

The reason I disagree is that "lexical `this`" is actually a new feature being added to the language -- in fact, it's the primary design motivation for arrows, not just a side effect -- so it clearly deserves to be highlighted. By contrast, the need for `return` in some cases like with `{ .. }` is a side-effect of grammar rules. `return` obviously isn't being added to the language here.

**Comment by lukehoban** [comment]
I made a slight tweak to the description of statement and expression bodies to make this a little clearer in 3d885921c2052befcef84db28c3b34fc038fd2a5.

**Pull request closed without merging**
